FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /Docker_App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Published -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /Docker_App
COPY --from=build-env /Docker_App/out .
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]